#cargo-features = ["edition2021"]

[package]
name = "rust_by_copypaste"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
errno="0.2.7"
